// Blocked words list — checked as substrings of the lowercased username.
// Keep sorted for readability. This is intentionally not exhaustive but covers
// the most common offensive terms and slurs.
const BLOCKED_WORDS = [
  'anal',
  'anus',
  'arse',
  'ass',
  'ballsack',
  'bastard',
  'bitch',
  'blowjob',
  'bollock',
  'boner',
  'boob',
  'butt',
  'chink',
  'clit',
  'cock',
  'coon',
  'crap',
  'cunt',
  'damn',
  'dick',
  'dildo',
  'dyke',
  'fag',
  'feck',
  'fellat',
  'fuck',
  'goddamn',
  'homo',
  'jerk',
  'jizz',
  'kike',
  'knob',
  'labia',
  'muff',
  'negro',
  'nigga',
  'nigger',
  'nonce',
  'nude',
  'penis',
  'piss',
  'poop',
  'porn',
  'prick',
  'pube',
  'pussy',
  'queer',
  'rape',
  'rectum',
  'retard',
  'scrot',
  'semen',
  'sex',
  'shit',
  'slut',
  'smegma',
  'spic',
  'spunk',
  'tit',
  'tosser',
  'turd',
  'twat',
  'vagina',
  'wank',
  'whore',
];

export function containsProfanity(username: string): boolean {
  const lower = username.toLowerCase();
  return BLOCKED_WORDS.some((word) => lower.includes(word));
}
